version: '3.8'

services:
  # 1. Baza Danych (Start od zera)
  db:
    image: postgres:15-alpine
    volumes:
      # Nowa nazwa wolumenu = czysta baza, bez błędów przeszłości
      - postgres_data_final_v3:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=animallogic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tajnehaslo123
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Django (Aplikacja)
  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && gunicorn animalLogic.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000
    environment:
      - SECRET_KEY=twoj_klucz_zmien_go_na_produkcji
      - DEBUG=1
      # Konfiguracja Bazy - TU JEST KLUCZ (używamy postgres)
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=animallogic
      - DB_USER=postgres
      - DB_PASSWORD=tajnehaslo123
      - DB_HOST=db
      - DB_PORT=5432
      # Adresy
      - ALLOWED_HOSTS=localhost,127.0.0.1,animal-server.local,192.168.31.161,animal.zipit.pl,www.animal.zipit.pl
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # 3. Nginx
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

  # 4. Tunel Cloudflare
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    # Tu jest Twój token z poprzednich logów
    command: tunnel run --token eyJhIjoiZTg4N2JmMTY2N2JjOTk1MDUwNWUyNDdlZGIzMjIzYWMiLCJ0IjoiNjhmNTdhMzMtNDM0Ni00NWJiLTg5YTAtNGYzZmU5YmEwOTJjIiwicyI6IlpqaGlabU5tWXpjdFltTmtPUzAwWlRRMkxUZ3dabVV0T0RCaE0yUmtZV0V3TVRaaCJ9
    depends_on:
      - nginx

volumes:
  postgres_data_final_v3:
  static_volume: