version: '3.8'

services:
  # 1. Baza Danych
  db:
    image: postgres:15-alpine
    volumes:
      # ZMIANA TUTAJ: Nowa nazwa wolumenu wymusi świeży start
      - postgres_data_new:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=animallogic
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=tajnehaslo123
    restart: always

  # 2. Django (Aplikacja)
  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && gunicorn animalLogic.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000
    environment:
      - SECRET_KEY=twoj_klucz_zmien_go_na_produkcji
      - DEBUG=1
      # Baza danych
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=animallogic
      - DB_USER=admin
      - DB_PASSWORD=tajnehaslo123
      - DB_HOST=db
      - DB_PORT=5432
      # Adresy
      - ALLOWED_HOSTS=localhost,127.0.0.1,animal-server.local,192.168.31.161,animal.zipit.pl,www.animal.zipit.pl
    depends_on:
      - db
    restart: always

  # 3. Nginx (Serwer WWW)
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

  # 4. Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run --token eyJhIjoiZTg4N2JmMTY2N2JjOTk1MDUwNWUyNDdlZGIzMjIzYWMiLCJ0IjoiNjhmNTdhMzMtNDM0Ni00NWJiLTg5YTAtNGYzZmU5YmEwOTJjIiwicyI6IlpqaGlabU5tWXpjdFltTmtPUzAwWlRRMkxUZ3dabVV0T0RCaE0yUmtZV0V3TVRaaCJ9
    depends_on:
      - nginx

volumes:
  # ZMIANA TUTAJ: Definicja nowego wolumenu
  postgres_data_new:
  static_volume: